# Generated by Django 5.2.3 on 2025-08-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hotelvendor_business_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoteluser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotelvendor',
            options={},
        ),
        migrations.AlterModelTable(
            name='hoteluser',
            table='Hotel_User',
        ),
        migrations.AlterModelTable(
            name='hotelvendor',
            table='Hotel_Vendor',
        ),
    ]
